In [1]:
import pandas as pd
import numpy as np

In [83]:
# 1.生成10名同学，5门功课的数据
score_df = pd.DataFrame(np.random.randint(40, 101, (10, 5)))
score_df

0   1    2    3   4
0  76  98   99   98  46
1  89  91   55   77  73
2  78  67   45   74  71
3  63  61  100   60  79
4  98  80   57   94  60
5  61  52   56   81  85
6  63  55   73   96  60
7  85  96   59   70  82
8  51  54   49  100  56
9  53  53   93   44  75

In [26]:
column_names = ['语文', '数学', '英语', '物理', '化学']
score_df.columns = column_names
score_df

语文  数学  英语  物理   化学
同学1   84  60  91  50   82
同学2   71  80  92  49   50
同学3   47  93  91  89   90
同学4   94  60  67  48  100
同学5   93  52  43  63   64
同学6   86  75  93  68   69
同学7   58  42  85  47   93
同学8   84  98  56  91   59
同学9   62  80  60  43   74
同学10  68  43  88  75   83

In [29]:
# [for i in range(1, 13)]       #  问题 ： 如何获取长度
# [i for i in range(len(score_df.index))]

# 获取表序列长度
# 方式一：len(score_df.index)
# print(len(score_df.index))
# 方式二：__len__()  采用魔法方法
# print(score_df.__len__())
# 方式三：score_df.shape[0]
# score_df.shape      # 获取的是表的行和列的数量  以元组的形式
# print(score_df.shape[0])

# print(score_df.size)        # 获取的是所有元素的个数  10行5列  (10*5)  50

index_names = ['同学' + str(i+1) for i in range(score_df.__len__())]
print(index_names)

10
['同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9', '同学10']


In [16]:
# colum_names 和 index_names 拼接

In [21]:
# 方式一：
score_df.columns = column_names
score_df.index = index_names
score_df

语文  数学  英语  物理   化学
同学1   84  60  91  50   82
同学2   71  80  92  49   50
同学3   47  93  91  89   90
同学4   94  60  67  48  100
同学5   93  52  43  63   64
同学6   86  75  93  68   69
同学7   58  42  85  47   93
同学8   84  98  56  91   59
同学9   62  80  60  43   74
同学10  68  43  88  75   83

In [30]:
# 方式二：rename 函数 可以实现对值的精准修改
score_df.rename(index={0:'同学1', 1:'同学2'},columns={0:'语文文',1:'数学学'}, inplace=True)
score_df

语文文  数学学    2   3   4
同学1   95   86   42  61  69
同学2   52   47   44  92  83
2     99   98   95  68  40
3     47   93   94  52  40
4     95   99   56  57  80
5     79   49   93  66  45
6     83   87  100  83  46
7     96   54   46  79  79
8     46   59   50  75  41
9     70   48   56  87  63

In [84]:
score_df.rename(
    index={i:index_names[i] for i in range(score_df.shape[0])},
    columns={i:column_names[i] for i in range(score_df.shape[1])},
    inplace=True
)
score_df

语文  数学   英语   物理  化学
同学1   76  98   99   98  46
同学2   89  91   55   77  73
同学3   78  67   45   74  71
同学4   63  61  100   60  79
同学5   98  80   57   94  60
同学6   61  52   56   81  85
同学7   63  55   73   96  60
同学8   85  96   59   70  82
同学9   51  54   49  100  56
同学10  53  53   93   44  75

### DataFrame 属性

In [46]:
# DataFrame 属性之index
print(score_df.index)       # 获取矩阵所有的索引

Index(['同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9', '同学10'], dtype='object')


In [47]:
# DataFrame 属性之columns
print(score_df.columns)       # 获取矩阵所有的列的名称

Index(['学科1', '学科2', '学科3', '学科4', '学科5'], dtype='object')


In [48]:
# DataFrame 属性之values
print(score_df.values)       # 获取矩阵所有的值

[[67 74 78 97 81]
 [90 78 75 99 49]
 [40 57 79 87 69]
 [55 73 44 92 59]
 [76 73 61 64 94]
 [92 67 78 90 63]
 [55 65 43 96 71]
 [56 61 81 56 87]
 [96 52 72 56 98]
 [96 57 76 67 65]]


In [91]:
# DataFrame 属性之转置
score_df.T       # 获取矩阵转置  行列转换

同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9  同学10
语文   76   89   78   63   98   61   63   85   51    53
数学   98   91   67   61   80   52   55   96   54    53
英语   99   55   45  100   57   56   73   59   49    93
物理   98   77   74   60   94   81   96   70  100    44
化学   46   73   71   79   60   85   60   82   56    75

### DataFrame 方法

In [62]:
# 从前向后展示 ，展示n行
# 如果输入的是 负数 例如 -m 为 从后去除m行，继续从前向后展示剩下的
# 1.head(n)     # n
score_df.head(-1)

语文  数学  英语  物理   化学
同学1  74  71  75  41   41
同学2  44  91  99  69  100
同学3  81  88  51  99   54
同学4  87  55  49  43   98
同学5  44  88  58  82   47
同学6  80  84  86  77   63
同学7  65  50  41  44   54
同学8  96  81  62  59   94
同学9  72  55  92  68   60

In [67]:
# 从后向前展示 ，展示n行
# 如果输入的是 负数 例如 -m 为 从前去除m行，继续从后向前展示剩下的
# 2.tail(n)     # n 默认是5
score_df.tail(6)

语文  数学  英语  物理  化学
同学5   44  88  58  82  47
同学6   80  84  86  77  63
同学7   65  50  41  44  54
同学8   96  81  62  59  94
同学9   72  55  92  68  60
同学10  91  61  48  78  78

In [68]:
# 3.info() 查看 df 对象的详情信息
#   第一行展示表示类型  例如：表示一个Pandas二维表格的数据结构DataFrame
#   第二行展示 共几行数据 索引标签 从哪到哪  例如：共10行数据， 索引标签为 同学1到同学9
#   第三行展示 一共几列      例如:共5列
#   展示 每列均有几个非空的值，数据完整是否有缺失     例如：每列均有10个非空的值，数据完整无缺失
#   展示 总内存占用多少字节  例如：总内存占用580字节
score_df.info()


<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 同学1 to 同学10
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   语文      10 non-null     int32
 1   数学      10 non-null     int32
 2   英语      10 non-null     int32
 3   物理      10 non-null     int32
 4   化学      10 non-null     int32
dtypes: int32(5)
memory usage: 280.0+ bytes


In [104]:
# describe  查看 df 对象的描述性统计信息
# 展示的信息为：
'''
数值型列（numeric columns）的统计信息：
    count: 非空值的数量
    mean: 平均值
    std: 标准差（反映数据的离散程度）
    min: 最小值
    25%：第一四分位数  （Q1，25% 的数据小于该值）
    50%：中位数       （Q2，50% 的数据小于该值）
    75%：第三四分位数  （Q3，75% 的数据小于该值）
    max：最大值
'''
"""
非数值型列（object/category 类型）的统计信息：
    count：非空值的数量
    unique：唯一值的数量
    top：出现最频繁的值（众数）
    freq：最频繁值（top）的出现次数
"""
# 1~100  1/4(25%)    2/4(中分位 50%)    3/4(75%)    4/4 max   四分位
#   四分法 ： 将数据切分为四分
score_df.describe()
'''
describe()方法 可选参数：
    include / exclude：指定包含或排除某些数据类型的列
        （如 include='all' 会显示所有列的统计信息）。
    percentiles：自定义百分位数
        （如 percentiles=[0.1, 0.5, 0.9]）。
    datetime_is_numeric：如果为 True，时间类型列也会像数值型列一样计算统计量。
'''


语文         数学          英语          物理        化学
count  10.000000  10.000000   10.000000   10.000000  10.00000
mean   71.700000  70.700000   68.600000   79.400000  68.70000
std    15.881855  18.797458   21.177556   18.301184  12.64955
min    51.000000  52.000000   45.000000   44.000000  46.00000
25%    61.500000  54.250000   55.250000   71.000000  60.00000
50%    69.500000  64.000000   58.000000   79.000000  72.00000
75%    83.250000  88.250000   88.000000   95.500000  78.00000
max    98.000000  98.000000  100.000000  100.000000  85.00000

In [101]:
# reset_index()     重置索引列
score_df.reset_index()      # 重置索引 为 0 ~ ....
# score_df.reset_index(drop=True)     # drop参数为：重置索引后是否保留原索引 ，默认为False 不删除要保留


index  语文  数学   英语   物理  化学
0   同学1  76  98   99   98  46
1   同学2  89  91   55   77  73
2   同学3  78  67   45   74  71
3   同学4  63  61  100   60  79
4   同学5  98  80   57   94  60
5   同学6  61  52   56   81  85
6   同学7  63  55   73   96  60
7   同学8  85  96   59   70  82
8   同学9  51  54   49  100  56
9  同学10  53  53   93   44  75

In [103]:
# 通过某一列的列名设置某一列为新索引
# score_df.set_index('语文',)      # 指定某一个列为索引
# score_df
score_df.set_index(["语文", "数学"])      # 指定某多个列为索引，传入列表形式

英语   物理  化学
语文 数学              
76 98   99   98  46
89 91   55   77  73
78 67   45   74  71
63 61  100   60  79
98 80   57   94  60
61 52   56   81  85
63 55   73   96  60
85 96   59   70  82
51 54   49  100  56
53 53   93   44  75