In [1]:
import pandas as pd
import numpy as np

In [53]:
# 1.生成10名同学，5门功课的数据
score_df = pd.DataFrame(np.random.randint(40, 101, (10, 5)))
score_df

0   1   2   3   4
0   58  78  87  50  49
1   43  71  42  91  88
2   66  68  46  65  83
3   62  57  75  99  89
4   87  60  83  70  86
5   59  56  44  73  55
6  100  64  85  61  41
7   97  60  49  89  47
8   92  74  66  65  66
9   48  80  63  40  65

In [26]:
column_names = ['语文', '数学', '英语', '物理', '化学']
score_df.columns = column_names
score_df

语文  数学  英语  物理   化学
同学1   84  60  91  50   82
同学2   71  80  92  49   50
同学3   47  93  91  89   90
同学4   94  60  67  48  100
同学5   93  52  43  63   64
同学6   86  75  93  68   69
同学7   58  42  85  47   93
同学8   84  98  56  91   59
同学9   62  80  60  43   74
同学10  68  43  88  75   83

In [29]:
# [for i in range(1, 13)]       #  问题 ： 如何获取长度
# [i for i in range(len(score_df.index))]

# 获取表序列长度
# 方式一：len(score_df.index)
# print(len(score_df.index))
# 方式二：__len__()  采用魔法方法
# print(score_df.__len__())
# 方式三：score_df.shape[0]
# score_df.shape      # 获取的是表的行和列的数量  以元组的形式
# print(score_df.shape[0])

# print(score_df.size)        # 获取的是所有元素的个数  10行5列  (10*5)  50

index_names = ['同学' + str(i+1) for i in range(score_df.__len__())]
print(index_names)

10
['同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9', '同学10']


In [16]:
# colum_names 和 index_names 拼接

In [21]:
# 方式一：
score_df.columns = column_names
score_df.index = index_names
score_df

语文  数学  英语  物理   化学
同学1   84  60  91  50   82
同学2   71  80  92  49   50
同学3   47  93  91  89   90
同学4   94  60  67  48  100
同学5   93  52  43  63   64
同学6   86  75  93  68   69
同学7   58  42  85  47   93
同学8   84  98  56  91   59
同学9   62  80  60  43   74
同学10  68  43  88  75   83

In [30]:
# 方式二：rename 函数 可以实现对值的精准修改
score_df.rename(index={0:'同学1', 1:'同学2'},columns={0:'语文文',1:'数学学'}, inplace=True)
score_df

语文文  数学学    2   3   4
同学1   95   86   42  61  69
同学2   52   47   44  92  83
2     99   98   95  68  40
3     47   93   94  52  40
4     95   99   56  57  80
5     79   49   93  66  45
6     83   87  100  83  46
7     96   54   46  79  79
8     46   59   50  75  41
9     70   48   56  87  63

In [54]:
score_df.rename(
    index={i:index_names[1] for i in range(score_df.shape[0])},
    columns={i:column_names[i] for i in range(score_df.shape[1])},
    inplace=True
)
score_df

语文  数学  英语  物理  化学
同学2   58  78  87  50  49
同学2   43  71  42  91  88
同学2   66  68  46  65  83
同学2   62  57  75  99  89
同学2   87  60  83  70  86
同学2   59  56  44  73  55
同学2  100  64  85  61  41
同学2   97  60  49  89  47
同学2   92  74  66  65  66
同学2   48  80  63  40  65

### DataFrame 属性

In [46]:
# DataFrame 属性之index
print(score_df.index)       # 获取矩阵所有的索引

Index(['同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9', '同学10'], dtype='object')


In [47]:
# DataFrame 属性之columns
print(score_df.columns)       # 获取矩阵所有的列的名称

Index(['学科1', '学科2', '学科3', '学科4', '学科5'], dtype='object')


In [48]:
# DataFrame 属性之values
print(score_df.values)       # 获取矩阵所有的值

[[67 74 78 97 81]
 [90 78 75 99 49]
 [40 57 79 87 69]
 [55 73 44 92 59]
 [76 73 61 64 94]
 [92 67 78 90 63]
 [55 65 43 96 71]
 [56 61 81 56 87]
 [96 52 72 56 98]
 [96 57 76 67 65]]


In [51]:
# DataFrame 属性之转置
score_df.T       # 获取矩阵转置  行列转换

同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9  同学10
学科1   67   90   40   55   76   92   55   56   96    96
学科2   74   78   57   73   73   67   65   61   52    57
学科3   78   75   79   44   61   78   43   81   72    76
学科4   97   99   87   92   64   90   96   56   56    67
学科5   81   49   69   59   94   63   71   87   98    65