In [2]:
import numpy as np
import pandas as pd

In [3]:
# 1.创建numpy对象ndarray
# 以下代码：
#   先创建一个一维数组 元素为0-14
#   再将一维数组变为三行五列
# [
#       [0,1,2,3,4],
#       [5,6,7,8,9],
#       [10,11,12,13,14]
# ]
arr1 = np.arange(15).reshape(3,5)
arr2 = np.arange(15)

In [4]:
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [34]:
print(f"numpy数组轴的个数：{arr1.ndim}")

a = np.array(1)
print("一位数的轴是：", a.ndim)

arr2 = np.arange(15)
print(f"一维数组的轴是：{arr2.ndim}")

my_list = [
    [[1,2,3],[1,2,3],[1,2,3]],
    [[8,9,10],[1,2,3],[1,2,3]],
    [[11,12,13],[1,2,3],[1,2,3]]
]
a = np.array(my_list)
print(f"三维数组的轴：a:{a.ndim}")

numpy数组轴的个数：2
一位数的维度是： 0
一维数组的维度是：1
三维数组的轴：a:3


In [33]:
print(f"numpy的维度：arr1:{arr1.shape}")
print(f"numpy的维度：arr2:{arr2.shape}")

a = np.array(1)
print(a)
print(type(a))
print(a.dtype)
print(f"一位数的维度：a:{a.shape}")

my_list = [
    [[1,2,3],[1,2,3],[1,2,3]],
    [[8,9,10],[1,2,3],[1,2,3]],
    [[11,12,13],[1,2,3],[1,2,3]]
]
a = np.array(my_list)
print(f"numpy的维度：a:{a.shape}")

numpy的维度：arr1:(3, 5)
numpy的维度：arr2:(15,)
1
<class 'numpy.ndarray'>
int32
一位数的维度：a:()
numpy的维度：a:(3, 3, 3)


In [1]:
print(f"numpy的元素的个数：{arr1.size}")

NameError: name 'arr1' is not defined

In [12]:
print(f"numpy的元素所占的字节数：{arr1.itemsize}")

numpy的元素所占的字节数：4


In [13]:
print(f"numpy的元素的类型：{arr1.dtype}")

numpy的元素的类型：int32


In [14]:
# 数组类型:numpy.ndarray 数组是numpy的容器
print(f"numpy的元素类型：{type(arr1)}")

numpy的元素类型：<class 'numpy.ndarray'>
