In [2]:
import pandas as pd
import numpy as np

# 创建ndarray对象
# 1.array()函数：可以把python的列表转换为->ndarray对象
my_list = [11,22,33,44,55,66]
print(type(my_list))

# 2.把python列表传入 array()  ---->  ndarray对象
arr1 = np.array(my_list)
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


# 1.arange()函数创建ndarray对象

In [2]:
# 1.创建ndarray对象   (包头不包尾)
arr3 = np.arange(0,10,2,dtype=np.int32)

In [7]:
print(arr3)
print(type(arr3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


# 2.随机数

## 2.1.random.rand 生成 0.0 ~ 1.0 之间的 包左不包右，随机小数矩阵

In [5]:
arr4 = np.random.rand(3,5)
print(arr4)

[[0.24768116 0.14380767 0.07821623 0.88930598 0.46428034]
 [0.74652494 0.70630189 0.24059068 0.80990128 0.07725235]
 [0.85675405 0.85820298 0.50448567 0.32963987 0.77199611]]


## 2.2.random.randint(起始值, 结束值, size = (行, 列)) 生成指定范围的，包左不包右，随机整数矩阵

In [6]:
arr5 = np.random.randint(3,9,size=(3,5))
print(arr5)

[[8 3 6 7 7]
 [5 3 3 6 3]
 [3 7 8 5 3]]


## 2.3.random.uniform(起始值, 结束值, size = (行, 列)) 生成指定范围的，包左不包右，随机多维浮点型矩阵

In [10]:
arr6 = np.random.uniform(-1,10,size=(3, 4))
print(arr6)

[[ 6.83803173  0.13556364  7.90016403  0.72033048]
 [ 5.8769138   3.71508997  1.67382643  1.01953789]
 [-0.83026167  9.74672912  1.74959121  1.47448981]]


## 2.4.指定数组的数据类型

In [14]:
#dtype参数，指定数组的数据类型，类型名+位数，如float64, int32
zeros_float_arr = np.zeros((3, 4), dtype=np.float64)
print(zeros_float_arr)
print(type(zeros_float_arr))
print(zeros_float_arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
float64


## 2.5.转换数组的数据类型

In [16]:
zeros_int_arr = zeros_float_arr.astype(np.int32)        # astype方法，转换数组的数据类型
print(zeros_int_arr)
print(type(zeros_int_arr))
print(zeros_int_arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<class 'numpy.ndarray'>
int32


# 3.等比数列

## 3.1.np.logspace等比数列

In [19]:
# logspace中，默认开始点和结束点是10的幂
a = np.logspace(0,0,10)         # 开始点为0 2^0  结束点为0 2^0  元素个数为10
print(a)
print(a.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


In [3]:
a = np.logspace(0,3,4)
print(a)

[   1.   10.  100. 1000.]


In [21]:
a = np.logspace(0,9,10)         # 0代表10的0次方，9代表10的9次方。
print(a)
print(a.dtype)
b = a.astype(np.int64)          # 不会改变之前的对象，只会产生新的对象
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
float64
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
float64
[         1         10        100       1000      10000     100000
    1000000   10000000  100000000 1000000000]
int64


In [23]:
# 改变基数，不让它以10为底数，可以改变base参数，将其设置为2
a = np.logspace(0, 9, 10, base=2)
print(a)
print(a.dtype)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
float64


# 4.等差数列

## 4.1.np.linspace等差数列

In [25]:
# np.linspace是用于创建一个一维数组，并且是等差数列构成的一维数组
#   最常用的三个参数:
#       第一个参数表示起始点，第二个参数表示终止点，第三个参数表示数列的个数。
a = np.linspace(1, 10, 10)
a = np.logspace(0,9,10)         # 0代表10的0次方，9代表10的9次方。
print(a)
print(a.dtype)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
float64


In [26]:
b = a.astype(np.int64)          # 不会改变之前的对象，只会产生新的对象
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
float64
[         1         10        100       1000      10000     100000
    1000000   10000000  100000000 1000000000]
int64


In [ ]:
# 参数endpoint用来决定是否包含终止值，默认值为True。
a = np.linspace(1, 10, endpoint=False)
print(a)
print(a.dtype)