In [1]:
import numpy as np
import pandas as pd

# Numpy 内置函数

## 1.基本函数

In [5]:
# randn() 返回具有标准正态分布的序列
arr = np.random.randn(2,3)
print(arr)
print("元素类型：",arr.dtype)        # 元素类型

[[ 0.67738573  0.11813069 -0.34836939]
 [-1.2640191   0.68498438  0.21878281]]
元素类型： float64


### (1).np.ceil(): 向上最接近的整数，参数是 number 或 array

In [7]:
b = np.ceil(arr)        # 天花板数  -->  向上取整
b
print(b)
print(type(b))
print(b.dtype)

[[ 1.  1. -0.]
 [-1.  1.  1.]]
<class 'numpy.ndarray'>
float64


### (2).np.floor(): 向下最接近的整数，参数是 number 或 array

In [6]:
b = np.floor(arr)       # 地板数 --> 向下取整
print(b)
print(type(b))
print(b.dtype)

[[ 0. -1. -1.]
 [-1.  1.  0.]]
<class 'numpy.ndarray'>
float64


### (3).np.rint(): 四舍五入，参数是 number 或 array

In [7]:
b = np.rint(arr)        # 四舍五入
print(b)
print(type(b))
print(b.dtype)

[[ 0. -1. -0.]
 [-0.  1.  1.]]
<class 'numpy.ndarray'>
float64


### (4).np.isnan(): 判断元素是否为 NaN(Not a Number)，参数是 number 或 array

In [8]:
b = np.isnan(arr)
print(b)
print(type(b))
print(b.dtype)

[[False False False]
 [False False False]]
<class 'numpy.ndarray'>
bool


### (5).np.multiply(): 元素相乘，参数是 number 或 array

In [10]:
b = np.multiply(arr,arr)        # 对应位置相乘
print(b)
print(type(b))
print(b.dtype)

[[0.13196029 0.94672655 0.01001222]
 [0.21124663 1.10627111 0.49206993]]
<class 'numpy.ndarray'>
float64


### (6).np.divide(): 元素相除，参数是 number 或 array

In [9]:
b = np.divide(arr,arr)      # 对应位置相除
print(b)
print(type(b))
print(b.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
float64


### (7).np.abs()：元素的绝对值，参数是 number 或 array

In [8]:
b = np.abs(arr)
print(b)
print(type(b))
print(b.dtype)

[[0.67738573 0.11813069 0.34836939]
 [1.2640191  0.68498438 0.21878281]]
<class 'numpy.ndarray'>
float64


### (8).np.where(condition, x, y): 三元运算符

In [17]:
# 等价于python的 x if condition else y
b = np.where(arr > 0 ,1 , -1)
print(arr)
print(b)
print(type(b))
print(b.dtype)

[[ 0.36326339 -0.97299874 -0.10006107]
 [-0.45961574  1.05179423  0.70147697]]
[[ 1 -1 -1]
 [-1  1  1]]
<class 'numpy.ndarray'>
int32


## 2.统计函数

In [11]:
arr = np.arange(12).reshape(3, 4)
print("数组：", arr)
#   多维数组默认统计全部维度，
#       axis参数可以按指定轴心统计，值为0则按列统计，值为1则按行统计。

# np.mean(), np.sum()：
#   所有元素的平均值，所有元素的和，参数是 number 或 array
print("平均值是：", np.mean(arr))     # 平均值
print("所有元素的和：", np.sum(arr))          # 所有元素的和
print("数组按列统计所有元素的和：", np.sum(arr, axis=0))      # 数组按列统计
print("数组按行统计所有元素的和：", np.sum(arr, axis=1))      # 数组按行统计

# np.max(), np.min()：
#   所有元素的最大值，所有元素的最小值，参数是 number 或 array


# np.std(), np.var()：
#   所有元素的标准差，所有元素的方差，参数是 number 或 array


# np.argmax(), np.argmin()：
#   最大值的下标索引值，最小值的下标索引值，参数是 number 或 array


# np.cumsum(), np.cumprod()：
#   返回一个一维数组，每个元素都是之前所有元素的 累加和 和 累乘积，参数是 number 或 array
print("所有元素的累加和：", np.cumsum(arr))        # 返回一个一维数组，每个元素都是之前所有元素的累加和

数组： [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5
所有元素的和： 66
数组按列统计所有元素的和： [12 15 18 21]
数组按行统计所有元素的和： [ 6 22 38]
所有元素的累加和： [ 0  1  3  6 10 15 21 28 36 45 55 66]


## 3.去重函数

In [23]:
arr = [[1, 2, 1], [2, 3, 4]]        # 2行3列

# np.unique():
#   找到唯一值并返回排序结果，类似于Python的set集合
a = np.array(arr)
print(a)
print(a.dtype)
b = np.unique(a)        # 返回一维数组
print(b)
print(b.dtype)

[[1 2 1]
 [2 3 4]]
int32
[1 2 3 4]
int32


## 4.排序函数

In [33]:
arr = np.array([1, 2, 34, 5])
print("原数组arr：", arr)

# np.sort() 函数排序，返回排序后的副本
sort_arr = np.sort(arr)
print("排序后的数组：", sort_arr)

# ndarray 直接调用sort，在原数据上进行修改
arr.sort()
print("数组.sort()方法排序：",arr)

# 逆序
sort_arr = np.argsort(-arr)
sortd_arr = arr[sort_arr]
print("逆序排序后的数组：", sortd_arr)

sortd_arr = np.sort(arr)[::-1]          # 先升序排序，再反转
print("逆序排序后的数组：", sortd_arr)

sortd_arr = np.flip(np.sort(arr))       # 先升序排序，再翻转
print("逆序排序后的数组：", sortd_arr)


arr = np.array([[3, 2], [4, 1]])
sortd_arr = np.sort(arr, axis=0)[::-1]  # 按列逆序排序
print("原数组：\n", arr)
print("逆序排序后的数组：\n", sortd_arr)


原数组arr： [ 1  2 34  5]
排序后的数组： [ 1  2  5 34]
数组.sort()方法排序： [ 1  2  5 34]
逆序排序后的数组： [34  5  2  1]
逆序排序后的数组： [34  5  2  1]
逆序排序后的数组： [34  5  2  1]
原数组：
 [[3 2]
 [4 1]]
逆序排序后的数组：
 [[4 2]
 [3 1]]
