In [1]:
import numpy as np
import pandas as pd

# Numpy 矩阵运算

## 1.基本运算

In [3]:
# 数组的算数运算是按照元素的。新的数组被创建并且被结果填充。
arr = np.array([20, 30, 40, 50])
print("原数组arr_1：", arr)
# arr_2 = np.arange(4)
arr_2 = np.array(4)
print("原数组arr_2：", arr_2)
c = arr - arr_2     # 对应元素相减      行列数相同
print("减法运算后的数组：", c)
c = arr + arr_2     # 对应元素相加
print("加法运算后的数组：", c)

原数组arr_1： [20 30 40 50]
原数组arr_2： 4
减法运算后的数组： [16 26 36 46]
加法运算后的数组： [24 34 44 54]


## 2 矩阵乘法 矩阵对应元素的乘法（multiplication by element-wise）

### (1).对应元素相乘

In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
c = a * b     # 对应元素相乘
print(c)
# 等价于
c = np.multiply(a,b)        # 对应元素相乘
print(c)

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


### (2).矩阵乘法

In [13]:
a = np.array([[1,2,3],[4,5,6]])             # 2 * 3 的矩阵
b = np.array([[6,23],[-1,7],[8,9]])         # 3 * 2 的矩阵

print(a)
print(b)

print(np.dot(a,b))
print(np.dot(b,a))

print(a.dot(b))         # 2 * 2
print(b.dot(a))         # 3 * 3

# 等价于
print(a @ b)        # 语法糖格式
print(b @ a)

# 语法糖对应的方法  __matmul__()
print(a.__matmul__(b))
print(b.__matmul__(a))


[[1 2 3]
 [4 5 6]]
[[ 6 23]
 [-1  7]
 [ 8  9]]
[[ 28  64]
 [ 67 181]]
[[ 98 127 156]
 [ 27  33  39]
 [ 44  61  78]]
