In [1]:
import numpy as np
import pandas as pd

# Numpy 运算

## 1.基本运算

In [3]:
# 数组的算数运算是按照元素的。新的数组被创建并且被结果填充。
arr = np.array([20, 30, 40, 50])
print("原数组arr_1：", arr)
arr_2 = np.arange(4)
print("原数组arr_2：", arr_2)
c = arr - arr_2
print("运算后的数组：", c)

原数组arr_1： [20 30 40 50]
原数组arr_2： [0 1 2 3]
运算后的数组： [20 29 38 47]


## 2 矩阵乘法 矩阵对应元素的乘法（multiplication by element-wise）

### (1).对应元素相乘

In [4]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
c = a*b     # 对应元素相乘
print(c)
# 等价于
c = np.multiply(a,b)        # 对应元素相乘
print(c)

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


### (2).矩阵乘法

In [5]:
a = np.array([[1,2,3],[4,5,6]])             # 2 * 3
b = np.array([[6,23],[-1,7],[8,9]])         # 3 * 2

print(a)
print(b)

print(a.dot(b))         # 2 * 2
print(b.dot(a))         # 3 * 3

[[1 2 3]
 [4 5 6]]
[[ 6 23]
 [-1  7]
 [ 8  9]]
[[ 28  64]
 [ 67 181]]
[[ 98 127 156]
 [ 27  33  39]
 [ 44  61  78]]
